### ISSUE TITLE
HA could not connect to vacuum

### ISSUE THREAD

**Issue by totti001** [pooyashahidi/xiaomi_vacuum#17]
I have this error at log. Xiaomi home can control it and the IP is valid.
`Logger: homeassistant.components.vacuum
Source: custom_components/xiaomi_vacuum/miio/miioprotocol.py:75
Integration: Vacuum (documentation, issues)
First occurred: 20:03:14 (1 occurrences)
Last logged: 20:03:14

xiaomi_vacuum: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 653, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 205, in status
    for prop in self.get_properties_for_mapping()
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 65, in get_properties_for_mapping
    return self.get_properties(
  File "/config/custom_components/xiaomi_vacuum/miio/device.py", line 269, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/config/custom_components/xiaomi_vacuum/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 162, in send
    self.send_handshake()
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 75, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
custom_components.xiaomi_vacuum.miio.exceptions.DeviceException: Unable to discover the device 192.168.1.51
`

**Comment by totti001** [comment]
After some reboot everything is working.
