### ISSUE TITLE
Dreame D9 - problem after firmware update

### ISSUE THREAD

**Issue by MikeColza** [pooyashahidi/xiaomi_vacuum#21]
After update vacuum firmware to 4.1.8_1132 HA stoped seeing the vacuum. 
Log from HA below:

Logger: homeassistant.components.vacuum
Source: custom_components/xiaomi_vacuum/miio/miioprotocol.py:242
Integration: Odkurzacz ([documentation], [issues]
First occurred: 09:15:48 (1 occurrences)
Last logged: 09:15:48
xiaomi_vacuum: Error on device update!

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 194, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 194, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 194, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 194, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 653, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 205, in status
    for prop in self.get_properties_for_mapping()
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 65, in get_properties_for_mapping
    return self.get_properties(
  File "/config/custom_components/xiaomi_vacuum/miio/device.py", line 269, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/config/custom_components/xiaomi_vacuum/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 234, in send
    return self.send(
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 234, in send
    return self.send(
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 234, in send
    return self.send(
  File "/config/custom_components/xiaomi_vacuum/miio/miioprotocol.py", line 242, in send
    raise DeviceException("No response from the device") from ex
custom_components.xiaomi_vacuum.miio.exceptions.DeviceException: No response from the device

**Comment by pooyashahidi** [comment]
Do you have this problem all the time? or was it a one time occurance?

**Comment by XaviosTheBoss** [comment]
Hello,
Just for your information, I had the same problem. I don't know if it's due to the firmware update, but the ip address of my robot had changed. So I changed it in my configuration (HA) and it works again.

**Comment by MikeColza** [comment]
It seems that firmware updated is changing token. Strange situation is that when i checking token it was like before. After all i deleted vacuum from mi home and add it again. After that token was diferent. Now everythink work fine on Home assistant. Unfortunetly i lost all my maps, data and schedules on mi home.

**Comment by pooyashahidi** [comment]
thanks for reporting this.
